# Generated by Django 5.2.1 on 2025-05-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_address_remove_user_hostel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('last_sent', models.DateTimeField(auto_now=True)),
                ('send_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
