# Generated by Django 5.2.1 on 2025-06-10 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpthrottle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('regular', 'Regular Customer'), ('mess_owner', 'Mess Owner')], max_length=20),
        ),
        migrations.CreateModel(
            name='MessOwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess_name', models.CharField(max_length=100)),
                ('business_address', models.TextField()),
                ('business_phone', models.CharField(blank=True, max_length=15)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mess_owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
