# Generated by Django 5.2.1 on 2025-06-24 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('welcome', 'Welcome Email'), ('profile_complete', 'Profile Completed'), ('subscription_created', 'Subscription Created'), ('payment_success', 'Payment Successful'), ('subscription_active', 'Subscription Activated'), ('subscription_cancelled', 'Subscription Cancelled'), ('subscription_expiring', 'Subscription Expiring'), ('leave_submitted', 'Leave Request Submitted'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('payment_failed', 'Payment Failed'), ('refund_processed', 'Refund Processed'), ('new_user_joined', 'New User Joined (Owner)')], max_length=50, unique=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Both')], default='email', max_length=10)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('email_template', models.TextField(blank=True)),
                ('sms_template', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=50)),
                ('channel', models.CharField(max_length=10)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_phone', models.CharField(blank=True, max_length=15)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_46a8ea_idx'), models.Index(fields=['status'], name='notificatio_status_a242db_idx')],
            },
        ),
    ]
