"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ
import dj_database_url
from celery.schedules import crontab

env = environ.Env()
env_file = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), '.env.development')
if os.path.isfile(env_file):
    env.read_env(env_file)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[
    'choolhachawka-production.up.railway.app',
    'localhost',
    '127.0.0.1',

])



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'rest_framework',
    'cloudinary_storage',
    'rest_framework_simplejwt.token_blacklist',
    'drf_yasg',
    'corsheaders',
    'cloudinary',                  
    # Local apps
    'accounts',
    'subscriptions',
    'payments',
    'notifications',
    'core',
    'feedback',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.RequestLoggingMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

AUTH_USER_MODEL = 'accounts.User'
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# Database Configuration - CORRECTED
if env('DATABASE_URL', default=None):
    # Production/Deployed
    DATABASES = {
        'default': dj_database_url.config(
            default=env('DATABASE_URL'),
            conn_max_age=600,
            engine='dj_db_conn_pool.backends.postgresql',
            # Connection pool settings for production
            conn_health_checks=True,
        )
    }
    
    # Fixed PostgreSQL options
    DATABASES['default']['OPTIONS'] = {
        'sslmode': 'require',
        'connect_timeout': 30,  # Increased from 10 to 30 seconds
        'application_name': 'choolha_chawka',
    }
    
    DATABASES['default']['ATOMIC_REQUESTS'] = True
    
else:
    # Local development
    DATABASES = {
        'default': {
            'ENGINE': 'dj_db_conn_pool.backends.postgresql',
            'NAME': env('DB_NAME', default='ChoolaChawka_dev'),
            'USER': env('DB_USER', default='postgres'),
            'PASSWORD': env('DB_PASSWORD', default='Himan123@'),
            'HOST': env('DB_HOST', default='localhost'),
            'PORT': env('DB_PORT', default='5432'),
            'CONN_MAX_AGE': 300,
            'ATOMIC_REQUESTS': True,
            'OPTIONS': {
                'connect_timeout': 30,  # Increased from 5 to 30 seconds
                'application_name': 'choolha_chawka_dev',
            }
        }
    }


# Additional database optimizations
DATABASE_CONN_HEALTH_CHECKS = True
DATABASE_CONN_MAX_AGE_JITTER = 60  # Add jitter to prevent connection storms


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'mediafiles')

# When using docker container
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'choola_chawka_db',
#         'USER': 'choola_user',
#         'PASSWORD': 'securepassword123',
#         'HOST': 'db',
#         'PORT': '5432',
#     }
# }

    
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True
USE_L10N = True
USE_TZ = True

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'staticfiles/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.AllowAny',
    ],
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    'https://ccf-end.vercel.app',
    'https://www.choolhachowka.com',
    'https://choolhachawka-production.up.railway.app'

])


CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[
    'https://ccf-end.vercel.app',
    'https://www.choolhachowka.com',
    'https://choolhachawka-production.up.railway.app'
    

])
CORS_ALLOW_CREDENTIALS = True

# Celery Configuration
REDIS_URL = env("REDIS_URL", default="redis://localhost:6379")

CELERY_BROKER_URL = CELERY_RESULT_BACKEND = REDIS_URL
CELERY_TASK_ALWAYS_EAGER = False

# Celery connection and timeout settings
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_CONNECTION_TIMEOUT = 30
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'socket_timeout': 30,
    'socket_connect_timeout': 30,
    'retry_on_timeout': True,
}

# Task execution settings
CELERY_TASK_SOFT_TIME_LIMIT = 300  # 5 minutes
CELERY_TASK_TIME_LIMIT = 600  # 10 minutes
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# Celery Beat Configuration for Periodic Tasks
CELERY_BEAT_SCHEDULE = {
    'update-expired-subscriptions': {
        'task': 'subscriptions.tasks.update_expired_subscriptions',
        'schedule': crontab(hour=0, minute=0),  # Run at midnight every day
    },
    'send-expiry-notifications': {
        'task': 'subscriptions.tasks.send_expiry_notifications',
        'schedule': crontab(hour=9, minute=0),  # Run at 9 AM every day
    },
    'cleanup-old-otp-records': {
        'task': 'accounts.tasks.cleanup_old_otp_records',
        'schedule': crontab(hour=2, minute=0),  # Run at 2 AM every day
    },
}

CELERY_TIMEZONE = 'Asia/Kolkata'

# Twilio settings
TWILIO_ACCOUNT_SID = env('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = env('TWILIO_AUTH_TOKEN')
TWILIO_PHONE_NUMBER = env('TWILIO_PHONE_NUMBER')

# Razorpay settings
RAZORPAY_KEY_ID = env('RAZORPAY_KEY_ID')
RAZORPAY_KEY_SECRET = env('RAZORPAY_KEY_SECRET')
RAZORPAY_WEBHOOK_SECRET = env('RAZORPAY_WEBHOOK_SECRET', default='')


STORAGES = {
  'default': {
    'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage' 
  },
  'staticfiles': {                                                 
    'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'   
  },
}


# Cloudinary Configuration
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': env('CLOUDINARY_CLOUD_NAME', default=''),
    'API_KEY': env('CLOUDINARY_API_KEY', default=''),
    'API_SECRET': env('CLOUDINARY_API_SECRET', default=''),
}

# Set Cloudinary as default file storage
# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Media settings (optional but recommended)
MEDIA_URL = '/media/'


# Resend Email Config - Using Resend Library instead of SMTP
RESEND_API_KEY = env('RESEND_API_KEY')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='noreply@choolhachowka.com')
SERVER_EMAIL = env('SERVER_EMAIL', default='noreply@choolhachowka.com')

# Keep SMTP as fallback (but we'll use Resend API primarily)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.resend.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'resend'
EMAIL_HOST_PASSWORD = RESEND_API_KEY
EMAIL_TIMEOUT = 30
EMAIL_USE_LOCALTIME = False

# Remove duplicate - already set above
SUPPORT_EMAIL = env('SUPPORT_EMAIL', default='Choolhachowka.com')
WHITENOISE_USE_FINDERS = True

FRONTEND_URL = env('FRONTEND_URL', default='http://localhost:5173')  # Placeholder URL
# WHITENOISE_USE_FINDERS = True

# Cache configuration (Redis backed)
CACHE_TTL = env.int('CACHE_TTL', default=120)  # seconds
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': env('REDIS_URL', default='redis://127.0.0.1:6379/1'),
        'TIMEOUT': env.int('CACHE_DEFAULT_TIMEOUT', default=300),
        'KEY_PREFIX': env('CACHE_KEY_PREFIX', default='cc'),
    }
}
NOTIFICATIONS_ASYNC = env.bool('NOTIFICATIONS_ASYNC', default=False)

# Logging configuration
LOG_LEVEL = env('LOG_LEVEL', default='INFO')
DJANGO_LOG_LEVEL = env('DJANGO_LOG_LEVEL', default='WARNING')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'app': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': env('DB_LOG_LEVEL', default='WARNING'),
            'propagate': False,
        },
        'rest_framework': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}