# Generated by Django 5.2.1 on 2025-06-08 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('service_type', models.CharField(choices=[('mess', 'Mess Eating'), ('tiffin', 'Tiffin Delivery')], max_length=10)),
                ('base_price', models.PositiveIntegerField()),
                ('included_meals', models.JSONField(default=list)),
                ('can_add_breakfast', models.BooleanField(default=True)),
                ('breakfast_addon_price', models.PositiveIntegerField(default=600)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['service_type', 'base_price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_included', models.BooleanField(default=False)),
                ('base_price', models.PositiveIntegerField()),
                ('breakfast_addon_price', models.PositiveIntegerField(default=0)),
                ('total_paid', models.PositiveIntegerField()),
                ('subscription_type', models.CharField(choices=[('mess', 'Mess Eating'), ('tiffin', 'Tiffin Delivery')], max_length=10)),
                ('start_date', models.DateField()),
                ('base_end_date', models.DateField()),
                ('adjusted_end_date', models.DateField()),
                ('leave_days', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('PENDING_PAYMENT', 'Pending Payment')], default='PENDING_PAYMENT', max_length=20)),
                ('payment_gateway', models.CharField(blank=True, max_length=30)),
                ('payment_transaction_id', models.CharField(blank=True, max_length=100)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount_calculated', models.PositiveIntegerField(default=0)),
                ('refund_status', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_start_date', models.DateField()),
                ('leave_end_date', models.DateField()),
                ('duration_days', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('AUTO_APPROVED', 'Auto Approved'), ('PENDING', 'Pending Approval'), ('REJECTED', 'Rejected')], default='AUTO_APPROVED', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
