# Generated by Django 5.2.1 on 2025-07-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_remove_leave_approved_at_remove_leave_rejected_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('PENDING_PAYMENT', 'Pending Payment'), ('RENEWED', 'Renewed')], default='PENDING_PAYMENT', max_length=20),
        ),
    ]
