# Generated by Django 5.2.1 on 2025-07-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_subscription_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='pending_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount currently pending payment (for renewals)', max_digits=8),
        ),
    ]
