# Generated by Django 5.2.1 on 2025-08-20 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('subscriptions', '0006_subscription_subscriptio_user_id_2a19e8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payments_pa_created_b8a300_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_gateway'], name='payments_pa_payment_86e34b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['amount'], name='payments_pa_amount_537f8d_idx'),
        ),
    ]
