# Generated by Django 5.2.1 on 2025-07-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackattachment',
            name='file',
            field=models.ImageField(upload_to='feedback_attachments/%Y/%m/'),
        ),
    ]
